.markdownlint.yml
Add config file to assist with local linting.
The Docker container used with our GHAWs already provides this file for CI use.
fixes GH-13
=> Add Markdownlint config file

go.mod
Replace upstream path with fork path.
fixes GH-3
=> go.mod | Update module URL to reflect fork

.github/workflows/lint-and-build-code.yml, .github/workflows/lint-and-test-only.yml
The golangci-lint config file in this repo is named with a different extension than I use elsewhere. Update the
GitHub Action Workflow files to reference the correct local filename for this repo.
=> Remove correct local lint config path in CI

send.go
Remove leading whitespace within `IsValidWebhookURL` helper func.
fixes GH-20
=> Fix whitespace linting error

send.go, send_test.go
Update table test to filter error result (nil or not) and then apply errors.As() func where non-nil to handle  wrapped errors.
I'm not particularly practiced at writing tests, so there is likely a better way to handle this.
This solves the immediate problem, but more work is needed to account for recent changes that I introduced with prior PRs accepted upstream (and now locally).
fixes GH-23
=> Replace IsType assert with Go 1.13 error wrapping

doc.go
Add package-level go.doc file to (mostly) replicate what the main README covers. This content features prominently on the main GoDoc page and also on pkg.go.dev.
- refs GH-24
- fixes GH-26
=> Extend GoDoc coverage

send_test.go
- unnecessary trailing newline
- unnecessary conversion
- Using the variable on range scope `test` in function literal
fixes GH-24
=> Fix misc linting issues surfaced in CI

README.md
- Link to both de-de Microsoft Teams references (existing)
and en-us (new)
- Replace "latest tag" badge with "latest release" badge
- this temporarily breaks the results, but will be
resolved once recent work is complete and a new
release is "cut" from the master branch
=> README | Minor tweaks to ref links, version badge

CHANGELOG.md
I've gone through and added releases to this fork for every existing upstream release. While doing so, I noticed that multiple changes have yet to be cut from master as a new release, so those have been added to the Unreleased section of this new CHANGELOG file.
fixes GH-32
=> Add CHANGELOG to reflect previous content

CHANGELOG.md
I missed this when preparing the v2.1.1 release.
fixes GH-36
=> Fix CHANGELOG section links

format.go
The content below was pulled from dasrick/go-teams-notify#16.
---
- Convert Windows/Mac/Linux EOL to Markdown break statements
- used to provide equivalent Teams-compatible formatting
- Format text as code snippet
- this inserts leading and trailing ` character to provide Markdown string formatting
- Format text as code block
- this inserts three leading and trailing ` characters to provide Markdown code block formatting
- *`Try`* variants of code formatting functions
- return formatted string if no errors, otherwise return the original string
I've implemented most of these functions primarily for use with several projects that submit code-heavy content to Microsoft Teams. These functions might be too project-specific for inclusion here, but I thought it would be best to get a clear …
=> Add formatting functions used for text conversion

send_test.go
Apply fix provided by `davecheney` in order to properly implement the RoundTripper interface's expected behavior:
- return response and nil error OR
- return nil and a non-nil error to explain failures to obtain a response
I likely *over* explained this with doc comments, but I am still very much in "learning" mode here.
- fixes GH-46
- 2ce144fffe3eab0da3282a80bc2a5ebdd58f1a42
- 6db6217e7daac6da6ed43dd7cf02032a22c84af2
- https://github.com/golang/go/issues/41071
- https://github.com/golang/go/issues/38095
- https://github.com/golang/go/commit/2d77d3330537e11a0d9a233ba5f4facf262e9d8c
- https://github.com/golang/go/commit/12d02e7d8e7df75ccbf07ec40028329fcc35c55b
- https://godoc.org/net/http#RoundTripper
- https://godoc.org/net/http#Response
- https://godoc.org/net/http#Response.Body
- …
=> Fix invalid test RoundTripper implementation

messagecard.go, send.go
Use package `init` function to create a global package logger
which is disabled by default. This logger can be enabled via
an exported `EnableLogging` function.
Use this new logger throughout portions of the codebase where
additional debugging context could prove useful.
fixes GH-38
=> Add package-level logger (disabled by default)

README.md
- Note the reasons why this fork is now standalone
- Link to list of forks
- Note near-future plans to incorporate content from
the `atc0005/send2teams` project
- the idea is to *move* that content here instead of
maintaining within that project
fixes GH-2
=> Update README to reflect this fork's status

send.go
- Port `SendMessage` func from `atc0005/send2teams/teams` package as `SendWithRetry` method
- Add SendWithRetry to API surface
Note: Still getting a linting warning for this new method's complexity, so likely require further work to simplify.
refs GH-52
=> Add SendWithRetry method to provide retry support

.github/workflows/lint-and-test-only.yml, Makefile
The Makefile doc comments make this clear that verbose
outut was the original intention.
Precursor to some test logic review work (where verbose output
will come in handy).
=> Enable verbose test output by default

send.go
Allow the `SkipWebhookURLValidationOnSend` method to modify the `skipWebhookURLValidation` field so that the intended behavior is applied.
refs GH-68
refs GH-69
refs GH-73
=> Adjust receiver type to permit field changes

send.go, send_test.go
- Add custom `ErrWebhookURLUnexpectedPrefix` error
- Use new error as wrapped error in validation function
- Update table test entry to use new error
- Cleanup/rework error type checking
- remove comment cruft left from prior debugging efforts
- use dedicated `targetErr` variable for use with `errors.As`
so that later usage of `test.error` operates on the
original value
- Explicitly verify that any errors which occur are expected
and any successful results are also expected
fixes GH-75
=> tests: Update err type check, assert results

README.md
- Update example text to assume Go Modules use
- Add example section, move existing example
- Add example of disabling webhook URL prefix validation
refs GH-68
=> README: Refresh examples, disable url prefix check

send.go
Instead of spinning off a new instance, use the existing client (receiver) where any desired client settings have likely already been applied.
In particular, this change allows the functionality added in GH-68 (`v2.4.0`) to work as intended.
fixes GH-83
=> SendWithRetry: Use receiver with existing settings

send.go
Use a regex to validate known webhook URL prefix patterns.
While a longer, very specific pattern has been tested and appears to work as intended, this commit replaces existing fixed string matches with one lighter regex that handles prefix matches.
refs GH-84
=> Modify webhook URL prefix validation to use regex

README.md, send.go
- README
- updates to better clarify webhook URL patterns
- add HowTo section for fetching webhook URLs
- Validation
- Rework validation to short circuit validation instead of
skipping only the prefix validation as before
- this better matches the intended/requested behavior
from GH-68
- Use fixed-string constant as an indicator that validation
has been disabled instead of a known/valid prefix pattern
(this might not matter now, but could avoid confusion if
logging what webhook URL was provided by client code)
fixes GH-84
=> Clarify application of webhook URL validation

README.md, messagecard.go, send.go, send_test.go
- `MessageCard` can now be validated with a custom validation func
- send `API` now supports custom webhook patterns for URL validation (added to the ability to deactivating it)
=> Better webhooks validation

.github/workflows/lint-docs.yml
Replace hard-coded version with LTS alias for "latest version", supported by the most recent `actions/setup-node` update.
refs GH-105
=> Update node-version val to use latest LTS version

.golangci.yml
- Replace deprecated linter `golint` with `revive`
- Replace deprecated linter `scopelint` with `exportloopref`
- Provide breadcrumb URL explaining why we are still using the
deprecated linter `maligned` instead of the recommended
`govet: fieldalignment` replacement linter
- Remove service config setting since we are not using the
upstream CI service, but rather GitHub Actions Workflow-based
CI (with custom Docker containers)
=> Replace golint, scopelint linters, cleanup cfg

messagecard.go
Added support for PotentialActions.
See https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#actions
=> Added structs to supports potential actions

messagecard.go
- Add new method for `MessageCardSection` to compliment
recently added method specific to the `MessageCard`.
- Add doc comment for `MessageCard.PotentialActions`
- was intended for last PR, but was overlooked
refs GH-102
=> Add `MessageCardSection.AddPotentialAction()` method

README.md, examples/actions/main.go, examples/basic/main.go, examples/custom-validation/main.go, examples/disable-validation/main.go
Move examples out of README so that CI checks can assert that the examples (at a minimum) still build correctly whenever repo content changes.
fixes GH-113
=> Migrate examples from README to standalone files

README.md, doc.go
- Remove example from doc.go file, direct reader to main README
- Update project status
- remove history as it is likely no longer relevant (original
project is discontinued at this point)
- remove future (for the same reason)
- Add explicit "Supported Releases" section to help make clear that
the v1 series is no longer maintained
- Move examples under common "Examples" header
- Remove explicit "used by" details, rely on dynamic listing provided
by pkg.go.dev instead
- Minor polish
=> Refresh documentation for new release

examples/actions/main.go
I evidently left the link refs intact when migrating examples from the main README file. This commit replaces them with a single "see also" URL.
=> Replace Markdown link refs with literal URL

README.md, doc.go, examples/custom-user-agent/main.go, send.go
- Apply project-speciifc default user agent to override the
Go default of `Go-http-client/1.1`
- set version based on when this project first diverged from
the parent project
- Offer override for client code
- Add brief example to illustrate setting custom user agent
fixes GH-134
=> Set project-specific user agent, offer override

messagecard.go
Incorrect field referenced in error message for `MessageCardSection.AddFact()`.
fixes GH-144
=> Fix incorrect field name reference in error msg

send.go
Changes:
- refactor `teamsClient.SendWithContext()`
-  break logic out into separate methods/functions to allow for reuse with upcoming work on alternative message payloads.
- further refactoring is intended
- refactor `teamsClient.SendWithRetry()`
- rework logic so that standard behavior of handling the error condition occurs first
- move expired context handling into error handling branch to make clear that we are really just dealing with error and and success evaluation
=> Refactor `teamsClient.SendWith*` methods

README.md, botapi/botapi.go, botapi/doc.go, doc.go, examples/actions/main.go, examples/custom-user-agent/main.go, examples/custom-validation/main.go, examples/disable-validation/main.go, examples/user-mention/main.go, messagecard/doc.go, messagecard/messagecard.go, send.go
- deprecate the current `API` interface
- expose `TeamsClient` to take its place
- create common interfaces and helper code to abstract any specific
Microsoft Teams message format
- create new `botapi` package (limited functionality)
- extend existing `MessageCard` type (where needed) type to support
new behavior
- port existing `goteamsnotify.MessageCard` types/functions/methods to
a new `messagecard` package and deprecate existing `MessageCard`
functionality provided by the `goteamsnotify` "base" package
- update examples to reflect changes
- restore support for overriding default `http.Client`
- restore default project-specific user agent, support for
overriding the default from client code
While making these changes I've refactored code and attempted to
clearly communicate which …
=> Deprecate API interface, add user mention support

messagecard/messagecard.go
I am planning to use this library with pre-built templates, provided by users, in YAML format. Due to the type of the `ValidateFunc` field of `MessageCard`, YAML decoding/encoding doesn't work out-of-the-box since the marshaller attempts to parse that field.
```go
// ValidateFunc is an optional user-specified validation function that is
// responsible for validating a MessageCard. If not specified, default
// validation is performed.
ValidateFunc func() error `json:"-"`
```
Furthermore, other fields such as `Type` and `Context` require that an extra `@` symbol is prefixed when encoding its value. Without effectively providing YAML tags, this is not feasible without re-implementing the structs in the client side. 
With this PR, clients of this library will be able to decode/encode the …
=> Added YAML en(de)coding support to `MessageCard`

adaptivecard/adaptivecard.go, internal/validator/doc.go, internal/validator/validator.go
- rename `validation` package back to original name of
`validator`
- attempting to follow the guideline of naming a package
based on what it provides, not what it does
- drop "Must" prefix from validation methods in an effort to make the
method names sound more natural
- add Validator.NoNilValuesInCollection method
- add validation handling for ColumnItems type alias ([]*Element)
- use Validator methods for validation of Column type
Further refactoring could be beneficial, as would further conversion
of Validate method implementations to use of the validator package.
refs GH-157
=> Further validation refactoring

send_test.go
Remove errors.As() comparison logic until I can determine how to use a table test configuration to reliably assert that an expected error is of a specific type.
Tweak test failure message format slightly to improve readability.
Add `name` field to table test struct, move test name comments from each table test into name value (so that each test case is properly labeled in output).
Run each test case as a subtest in an effort to provide additional isolation.
fixes GH-176
=> Remove invalid errors.As() usage, name test cases

adaptivecard/adaptivecard.go
Update the JSON key name to match the field name. I mistakenly used the property type for the field instead of the field name itself.
fixes GH-179
=> Fix invalid JSON key name for Element.URL field

.github/workflows/codeql-analysis.yml, .github/workflows/lint-and-build-code.yml, .github/workflows/lint-and-test-only.yml, .github/workflows/lint-docs.yml, Makefile
- echo golangci-lint version
- echo staticcheck version
- echo markdownlint-cli version
- add `go_mod_changes` job to test for uncommitted `go mod tidy`
and `go mod vendor` changes
- add CodeQL GitHub Actions Workflow
=> Update Makefile and GitHub Actions Workflows

adaptivecard/adaptivecard.go, adaptivecard/doc.go, doc.go, internal/validator/doc.go
- remove stray whitespace per Go 1.19 fmt linting rules
- apply Go 1.19 specific doc comment syntax changes to doc.go
file at project root
=> Apply Go 1.19 specific doc comments linting fixes

adaptivecard/adaptivecard.go
Based on current documentation and brief testing, schema version 1.5 appears to now be supported by Teams Incoming Webhook Connectors.
refs GH-205
=> Update AdaptiveCardMaxVersion to 1.5

internal/validator/validator.go
Update handling of valid values list to explicitly consider an empty list to compare against as false.
This was already the case based on the use of a helper function's logic (`goteamsnotify.InList`), but this was not handled/noted explicitly.
=> Update `InList`, `InListIfFieldValNotEmpty` validators

Makefile
Add this alias to match other projects that I maintain (match shared CI task expectations).
=> Add `quick` Makefile recipe (alias)

README.md, adaptivecard/adaptivecard.go, adaptivecard/getters.go, examples/adaptivecard/table-manually-created/main.go, examples/adaptivecard/table-unordered-grid/main.go, examples/adaptivecard/table-with-headers/main.go
Add early implementation of Adaptive Card Table support.
- Expand base/shared Element type with fields specific to the Table type
- Refresh documentation for Column type to note that it serves a dual role
- member of a ColumnSet
- member of a Table (TableColumnDefinition)
- Add new types specific to tables
- Examples
- add example of manually creating a table
- add example of creating a table with headers
- add example of creating a table of unordered "grid" values
- README
- Add references to new examples
- Add Table element documentation reference
Support for Adaptive Card Table elements is new. There are likely sharp edges and missing support. [Feedback is welcome](https://github.com/atc0005/go-teams-notify/issues/205).
- refs GH-205
- https://adaptivecards.io/explorer/Table.html
=> Add initial Adaptive Card Table support

README.md, examples/adaptivecard/proxy/main.go, examples/messagecard/proxy/main.go
Add examples of specifying a proxy server for:
- MessageCard format
- Adpative Card format
Thanks to @ahfa92 for the idea and testing feedback.
refs GH-240
=> Add proxy server examples

adaptivecard/adaptivecard.go, adaptivecard/doc.go, adaptivecard/format.go, messagecard.go, messagecard/doc.go, messagecard/format.go, messagecard/messagecard.go
- use bullet lists for collections of URLs
- add whitespace to help separate URLs (where needed)
- use link references
More opportunities for cleanup remain.
=> Update Go Doc comment formatting

README.md, adaptivecard/adaptivecard.go, examples/adaptivecard/toggle-visibility-column-action/main.go, examples/adaptivecard/toggle-visibility-container-action/main.go, examples/adaptivecard/toggle-visibility-multiple-buttons/main.go, examples/adaptivecard/toggle-visibility-single-button/main.go
- add Element.Visible field
- to control visibility of Elements
- if not specified, this value defaults to true by omitting the field from the generated JSON payload
- add TargetElement type
- add Action.TargetElement field
- to specify collection of TargetElement values
- used to specify target Element values whose visibility state should be controlled by the Element whose Action the TargetElement field is associated with
- add ISelectAction.TargetElements field
- same purpose as Action.TargetElement field
- add missing validation for Element.SelectAction field for Element of ColumnSet type
- add missing validation for Element.SelectAction field for Element of Container type
- add Column.AddSelectAction method
- accepts Action or ISelectAction value
- update ISelectAction.Validate method …
=> Initial support for toggling visibility

adaptivecard/adaptivecard.go, adaptivecard/getters.go
This PR adds two fields to the `Element` struct:
- `IsSubtle`: For setting subtle text appearance
- `HorizontalAlignment`: For setting the horizontal alignment of text elements
Reference: https://adaptivecards.io/explorer/TextBlock.html
I reused the horizontal alignment values from `Column.HorizontalCellContentAlignment` as the values are the same and I felt that having something like `HorizontalTextAlignmentLeft` would cause confusion when the field itself is called `HorizontalAlignment`.
Closes #254
=> Add `IsSublte` and `HorizontalAlignment` to `Element`

README.md
- add directions for creating new Power Automate workflow connectors
- heavily emphasize deprecation of legacy MessageCard format and O365 connectors
- update Supported Release section to share plans for current v2 series and upcoming v3 series
- GH-262
=> Documentation refresh for Workflow connectors

adaptivecard/adaptivecard.go, send.go
- lower `AdaptiveCardMaxVersion` from `1.5` to `1.4`
- this almost seems like a bug on Teams' end as this limitation is not communicated (from what I could tell) via https://adaptivecards.io/designer/
- using a value of `1.4` appears to work equally well for O365 and Workflow connectors
- treat a 202 response code as sufficient response verification
- instead of expecting a `1` in the response body as previously confirmed
- see also atc0005/go-teams-notify#59
- add `logic.azure.com` to valid URL patterns for default validation
- debugging / troubleshooting - log status code and response string for O365 connector responses - log validation pattern match
- GH-262
=> Add initial support for Workflow connectors

.github/dependabot.yml, .golangci.yml, CHANGELOG.md
Retain recent README changes, accept other changes.
Last commit to master branch: 31c27ee9ea119a026010286193e24d4b1a3e870f
=> Sync latest changes from master branch

adaptivecard/adaptivecard.go
The now removed error handling was used prior to refactoring applied in commit 7ef6d5203f760f07ad704fb027f4f7ff2696fcc8.
credit: Thanks to @ArcticXWolf for reporting this.
- GH-268
- GH-251
=> Fix validation for `Action.Type` field

README.md
Update README coverage with updated details regarding the deprecation timeline and current plans for v2 and v3 release series.
refs GH-262
=> Update O365 deprecation timeline details

README.md
- add directions for creating new Power Automate workflow connectors
- heavily emphasize deprecation of legacy MessageCard format and O365 connectors
- update Supported Release main section and subsections to share plans for current v2 series and future v3 series
- provide updated O365 deprecation timeline details (December 2024, December 2025)
- GH-262
=> Documentation refresh for O365 & Workflow connectors

send.go
Switch from static base pattern of `logic.azure.com` to a regex OR pattern to permit either of `logic.azure.com` or `*.azure-api.net` as has been observed in the wild.
This also has the side effect of resolving potential CodeQL alerts raised in PR GH-275.
refs GH-262
=> Refactor regex for default Workflow URLs

send.go
THIS is the regex pattern intended for GH-277.
Previous commit message:
Switch from static base pattern of `logic.azure.com` to a regex OR pattern to permit either of `logic.azure.com` or `*.azure-api.net` as has been observed in the wild.
This also has the side effect of resolving potential CodeQL alerts raised in PR GH-275.
refs GH-262
=> Refactor regex for default Workflow URLs (redux)

.github/workflows/codeql.yml
Run CodeQL jobs for `development` branch in addition to the current stable branch.
refs GH-276
=> Update CodeQL workflow to run on dev branch PRs

send.go
Export the `TeamsMessage` interface type to better support abstracting/mocking the functionality of this library by dependent projects.
- the fields of the interface are intentionally not exported so as to help prevent future changes/improvements from breaking client code
- this change is considered a non-breaking change as the support for creating message types compliant with this interface is unchanged
- GH-285
=> Expose `TeamsMessage` interface to support mocking

adaptivecard/adaptivecard.go, adaptivecard/getters.go
This adds support for the extension element [CodeBlock](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cdesktop%2Cconnector-html#codeblock-in-adaptive-cards).
=> Add MSTeams CodeBlock element

README.md, adaptivecard/adaptivecard.go, examples/adaptivecard/codeblock/main.go
- add `examples/adaptivecard/codeblock`
- update README file to mention new CodeBlock support
- minor linting fixes
- minor doc comment adjustments to list supported programming languages for CodeBlock element
- fixes GH-288
=> Update documentation for CodeBlock element
