atc0005/go-teams-notify

Makefile
Update/replace with a copy of the Makefile I use in my other projects and which newly added GitHub Actions
Workflows expect to find in this repo.
fixes GH-18
=> Replace Makefile

README.md
- Add badges to reflect the latest workflow results
- Link each badge to the applicable workflow results
fixes GH-7
=> README | Add GitHub Actions workflow badges

README.md
- Link back to this project as an authoritative source
- Add Features section
- Add CHANGELOG section (see GH-32)
- Add links to related projects (mostly projects that use this library)
fixes GH-4
=> Update README to reflect current project status

send.go, send_test.go
Extend error handling by retrieving and providing the
response string from the remote API as part of the error
message returned to the caller if the status code
indicates an error condition.
Based on testing, the response string contains useful
troubleshooting information which can help identify
missing information in the submitted MessageCard payload.
fixes GH-41
=> Remote API error handling: expose response string

send.go
- Add `SendWithContext` method, extend `API` interface to expose it for use.
- Modify existing `Send`method to create a context using the previous timeout value, then act as a wrapper that calls `SendWithContext` with this new context.
The net effect is that existing clients get a `Send` method with the same timeout value as before, but also get an optional `SendWithContext` method which allows for easily applying a custom timeout/cancellation behavior.
fixes GH-40
=> Extend API to allow request cancellation via ctx

format.go
These changes are based on work from the atc0005/send2teams project.
refs GH-52
=> Add package-level logging for formatting funcs

send.go
Reduce complexity by:
- converting multiple if statements to a switch block
- using early return
- combine some conditionals so reduce duplicate logic checks
Overall, the `SendWithRetry` function implementation is now simpler than before. Yay for linting?
fixes GH-55
=> Reduce cognitive complexity of SendWithRetry func

send.go
Fix gocritic commentFormatting linting complaint regarding lack of initial leading space.
=> Minor comment formatting linting fix

.gitignore, .golangci.yml, .markdownlint.yml, doc.go, go.mod, messagecard.go, send.go, send_test.go
Evidently a victim of a stray search/replace in the past.
=> Fix breadcrumb URLs

README.md
=> Replace godoc.org badge with pkg.go.dev badge

send_test.go
=> Extend tests to cover optional URL validation

README.md
Attempt to give potential future users of the library a sense of why this fork exists and what the long-term goals are.
=> README: refresh current status, expand on history

README.md
- Restore notes for example of disabling webhook validation
- Add notes for custom webhook URL validation
refs GH-93
=> Updates notes for recent examples

README.md
- Provide static list
- with the assumption that it will be periodically updated
- Provide links to pkg.dev dynamic lists
- Remove explicit links to some of my projects under
References section, move to "Used by" section
fixes GH-95
=> Add section to list dependent projects

README.md
Note features added since this fork was made
Unrelated: section header rename.
=> Update features list

messagecard.go
- Add doc comments where needed
- Reorder struct fields to resolve `maligned` linter complaints
- Formatting tweaks
- intended to match existing code formatting (e.g., whitespace,
line wrapping, etc)
refs GH-102
=> Fix linting errors, adjust formatting

messagecard.go
Add two helper functions to handle:
- validation of `*MessageCardPotentialAction` values
- appending `*MessageCardPotentialAction` values to the
`PotentialAction` field for both `MessageCard` and
`MessageCardSection` values
The `NewMessageCardPotentialAction` factory function has been
modified to return an `error`. This provides validation at both
entry points:
- creating a new value
- adding a value to an existing collection
**NOTE:**
This change is considered to be compatible with semantic
versioning because the support for `PotentialActions` has not
yet landed in a stable public release, leaving the final form
subject to change until the next public release.
fixes GH-102
=> Extend MessageCardPotentialAction validation

README.md, doc.go
- Update features list
- Add example
fixes GH-111
=> Refresh docs to cover new PotentialActions support

.github/dependabot.yml, .github/workflows/lint-and-build-code.yml, .github/workflows/lint-and-build-using-make.yml, .github/workflows/lint-and-test-only.yml, .github/workflows/lint-docs.yml, .gitignore, .markdownlint.yml, Makefile, doc.go, format.go, go.mod, messagecard.go, send.go, send_test.go
I've heard mixed perspectives on whether this is needed, either
at all, just on recently modified files or project-wide. I
don't know enough to say for sure which approach is valid, so
I am opting to search/replace across the project for now until I
learn differently.
=> Update copyright date

send.go
=> Fix "nilness: tautological condition" linting err

CHANGELOG.md
Rearrange some entries for new release
=> Minor CHANGELOG formatting tweaks

.github/dependabot.yml, README.md, adaptivecard/adaptivecard.go, adaptivecard/doc.go, adaptivecard/format.go, examples/adaptivecard/proxy/main.go, examples/messagecard/proxy/main.go, messagecard.go, messagecard/doc.go, messagecard/format.go, messagecard/messagecard.go
daebc600a949834c1d616fded6ba22b8e94282fa
=> Sync latest changes from master branch

adaptivecard/adaptivecard.go, adaptivecard/getters.go
Syncing changes from commit 62369585e9caf08d27c078fdc88f51232057a941 (applied to `master` branch) to `development` branch.
=> Add `IsSublte` and `HorizontalAlignment` to `Element`
